// ────────────────────────────────────────
//   СОЗДАНИЕ ВСЁ СЕТКИ 30×25
// ────────────────────────────────────────
const game = document.getElementById("game");
const container = document.getElementById("container");
const summaryBar = document.getElementById("summaryBar");
const playerSlotLeft = document.getElementById("playerSlotLeft");
const playerSlotRight = document.getElementById("playerSlotRight");
const resourceCountdown = document.getElementById("resourceCountdown");
const resourceCountdownLeft = document.getElementById("resourceCountdownLeft");
const resourceCountdownRight = document.getElementById("resourceCountdownRight");
const treasureState = document.getElementById("treasureState");
const treasureStateRight = document.getElementById("treasureStateRight");
const rollBtn = document.getElementById("rollBtn");
const endTurnBtn = document.getElementById("endTurnBtn");
const newGameBtn = document.getElementById("newGameBtn");
const turnInfo = document.getElementById("turnInfo");
const rollInfo = document.getElementById("rollInfo");
const movesInfo = document.getElementById("movesInfo");
const doubleMsg = document.getElementById("doubleMsg");
const currentPlayerName = document.getElementById("currentPlayerName");
const pickupToast = document.getElementById("pickupToast");
const pickupText = document.getElementById("pickupText");
const doubleToast = document.getElementById("doubleToast");
const barracksModal = document.getElementById("barracksModal");
const barracksClose = document.getElementById("barracksClose");
const barracksButtons = Array.from(document.querySelectorAll("[data-buy]"));
const lavkaModal = document.getElementById("lavkaModal");
const lavkaClose = document.getElementById("lavkaClose");
const lavkaButtons = Array.from(document.querySelectorAll("[data-lavka-buy]"));
const workshopModal = document.getElementById("workshopModal");
const workshopClose = document.getElementById("workshopClose");
const workshopButtons = Array.from(document.querySelectorAll("[data-workshop-buy]"));
const hireModal = document.getElementById("hireModal");
const hireClose = document.getElementById("hireClose");
const hireButtons = Array.from(document.querySelectorAll("[data-hire]"));
const repairModal = document.getElementById("repairModal");
const repairConfirm = document.getElementById("repairConfirm");
const repairCancel = document.getElementById("repairCancel");
const repairText = document.getElementById("repairText");
const messengerModal = document.getElementById("messengerModal");
const messengerConfirm = document.getElementById("messengerConfirm");
const messengerCancel = document.getElementById("messengerCancel");
const messengerModalText = document.getElementById("messengerModalText");
const gameOverModal = document.getElementById("gameOverModal");
const gameOverText = document.getElementById("gameOverText");
const gameOverClose = document.getElementById("gameOverClose");
const cityModal = document.getElementById("cityModal");
const cityClose = document.getElementById("cityClose");
const cityRewardButtons = Array.from(document.querySelectorAll("[data-city-reward]"));
const cityExchangeButtons = Array.from(document.querySelectorAll("[data-city-exchange]"));
const cityKillsInfo = document.getElementById("cityKillsInfo");
const turnCounterDisplay = document.getElementById("turnCounter");
const timeOfDayDisplay = document.getElementById("timeOfDay");
const turnsUntilTimeChangeDisplay = document.getElementById("turnsUntilTimeChange");
const gameTimerDisplay = document.getElementById("gameTimer");
const playerPanels = Array.from(document.querySelectorAll(".player-panel"));
const inventoryPanels = Array.from(document.querySelectorAll(".inventory-panel"));
const playerColorDots = Array.from(document.querySelectorAll(".player-color"));
const guardModal = document.getElementById("guardModal");
const guardBribeBtn = document.getElementById("guardBribeBtn");
const guardInfluenceBtn = document.getElementById("guardInfluenceBtn");
const guardPassBtn = document.getElementById("guardPassBtn");
const guardModalCancel = document.getElementById("guardModalCancel");
const robberModal = document.getElementById("robberModal");
const robberModalText = document.getElementById("robberModalText");
const robberFightBtn = document.getElementById("robberFightBtn");
const robberBribeBtn = document.getElementById("robberBribeBtn");
const robberBribeInfo = document.getElementById("robberBribeInfo");
const robberCount = document.getElementById("robberCount");
const stoneModal = document.getElementById("stoneModal");
const stoneTouchBtn = document.getElementById("stoneTouchBtn");
const stonePickupBtn = document.getElementById("stonePickupBtn");
const stoneResultModal = document.getElementById("stoneResultModal");
const stoneResultText = document.getElementById("stoneResultText");
const stoneResultClose = document.getElementById("stoneResultClose");
const damageToast = document.getElementById("damageToast");
const trollCaveModal = document.getElementById("trollCaveModal");
const trollCaveText = document.getElementById("trollCaveText");
const trollCaveClose = document.getElementById("trollCaveClose");
const barbarianRaidModal = document.getElementById("barbarianRaidModal");
const barbarianRaidText = document.getElementById("barbarianRaidText");
const barbarianRaidClose = document.getElementById("barbarianRaidClose");
const caveEntranceChoiceModal = document.getElementById("caveEntranceChoiceModal");
const caveEntranceChoiceText = document.getElementById("caveEntranceChoiceText");
const caveEnterBtn = document.getElementById("caveEnterBtn");
const caveAttackBtn = document.getElementById("caveAttackBtn");
const timeOfDayModal = document.getElementById("timeOfDayModal");
const timeOfDayModalTitle = document.getElementById("timeOfDayModalTitle");
const timeOfDayModalContent = document.getElementById("timeOfDayModalContent");
const timeOfDayModalClose = document.getElementById("timeOfDayModalClose");
const masterModal = document.getElementById("masterModal");
const masterBuyHilt = document.getElementById("masterBuyHilt");
const masterBuyGold = document.getElementById("masterBuyGold");
const masterBuyToken = document.getElementById("masterBuyToken");
const masterBuyGoldRainbow = document.getElementById("masterBuyGoldRainbow");
const masterBuyTerrorRing = document.getElementById("masterBuyTerrorRing");
const masterCloseBtn = document.getElementById("masterCloseBtn");
const tavernModal = document.getElementById("tavernModal");
const tavernGoldValue = document.getElementById("tavernGoldValue");
const tavernStatus = document.getElementById("tavernStatus");
const tavernDrinkBeerBtn = document.getElementById("tavernDrinkBeerBtn");
const tavernWheelBtn = document.getElementById("tavernWheelBtn");
const tavernDragonBtn = document.getElementById("tavernDragonBtn");
const tavernCloseBtn = document.getElementById("tavernCloseBtn");
const tavernWheelModal = document.getElementById("tavernWheelModal");
const tavernFortuneWheel = document.getElementById("tavernFortuneWheel");
const tavernWheelGoldValue = document.getElementById("tavernWheelGoldValue");
const tavernWheelPlaysValue = document.getElementById("tavernWheelPlaysValue");
const tavernWheelBetInput = document.getElementById("tavernWheelBetInput");
const tavernWheelColorButtons = Array.from(document.querySelectorAll("[data-tavern-wheel-color]"));
const tavernWheelSpinBtn = document.getElementById("tavernWheelSpinBtn");
const tavernWheelStatus = document.getElementById("tavernWheelStatus");
const tavernWheelBackBtn = document.getElementById("tavernWheelBackBtn");
const tavernDragonModal = document.getElementById("tavernDragonModal");
const tavernDragonGoldValue = document.getElementById("tavernDragonGoldValue");
const tavernDragonPlaysValue = document.getElementById("tavernDragonPlaysValue");
const tavernDragonBetInput = document.getElementById("tavernDragonBetInput");
const tavernDragonStartBtn = document.getElementById("tavernDragonStartBtn");
const tavernDragonCashoutBtn = document.getElementById("tavernDragonCashoutBtn");
const tavernDragonStatus = document.getElementById("tavernDragonStatus");
const tavernDragonBackBtn = document.getElementById("tavernDragonBackBtn");
const tavernFishkaBtn = document.getElementById("tavernFishkaBtn");
const tavernFishkaModal = document.getElementById("tavernFishkaModal");
const tavernFishkaWheel = document.getElementById("tavernFishkaWheel");
const tavernFishkaCountValue = document.getElementById("tavernFishkaCountValue");
const tavernFishkaPlaysValue = document.getElementById("tavernFishkaPlaysValue");
const tavernFishkaSpinBtn = document.getElementById("tavernFishkaSpinBtn");
const tavernFishkaStatus = document.getElementById("tavernFishkaStatus");
const tavernFishkaBackBtn = document.getElementById("tavernFishkaBackBtn");
const dragonCrashStage = document.getElementById("dragonCrashStage");
const dragonCrashSprite = document.getElementById("dragonCrashSprite");
const dragonCrashMultiplier = document.getElementById("dragonCrashMultiplier");
const battleModal = document.getElementById("battleModal");
const battleSummary = document.getElementById("battleSummary");
const battleClose = document.getElementById("battleClose");
const playerBattleCardModal = document.getElementById("playerBattleCardModal");
const playerBattleCardTitle = document.getElementById("playerBattleCardTitle");
const playerBattleCardStatus = document.getElementById("playerBattleCardStatus");
const playerBattleCards = document.getElementById("playerBattleCards");
const worldEventModal = document.getElementById("worldEventModal");
const worldEventTitle = document.getElementById("worldEventTitle");
const worldEventText = document.getElementById("worldEventText");
const worldEventClose = document.getElementById("worldEventClose");
const kingAuctionModal = document.getElementById("kingAuctionModal");
const kingAuctionDescription = document.getElementById("kingAuctionDescription");
const kingAuctionOfferCards = Array.from(document.querySelectorAll("[data-king-auction-player]"));
const kingAuctionInputElems = Array.from(document.querySelectorAll("[data-king-auction-input]"));
const kingAuctionSubmitButtons = Array.from(document.querySelectorAll("[data-king-auction-submit]"));
const kingGenerosityModal = document.getElementById("kingGenerosityModal");
const kingGenerosityDescription = document.getElementById("kingGenerosityDescription");
const kingGenerosityOfferCards = Array.from(document.querySelectorAll("[data-king-generosity-player]"));
const kingGenerosityChoiceButtons = Array.from(document.querySelectorAll("[data-king-generosity-player-choice]"));
const castleModal = document.getElementById("castleModal");
const castleLevelValue = document.getElementById("castleLevelValue");
const castleArmorValue = document.getElementById("castleArmorValue");
const castleHealthValue = document.getElementById("castleHealthValue");
const castleNextBonus = document.getElementById("castleNextBonus");
const castleUpgradeBtn = document.getElementById("castleUpgradeBtn");
const castleUpgradeCostLabel = document.getElementById("castleUpgradeCost");
const castleBuilderChargeBtn = document.getElementById("castleBuilderChargeBtn");
const castleBuilderChargeRow = document.getElementById("castleBuilderChargeRow");
const castleModalClose = document.getElementById("castleModalClose");
const castleWallBadge = document.getElementById("castleWallBadge");
const castleWithdrawInput = document.getElementById("castleWithdrawInput");
const castleWithdrawBtn = document.getElementById("castleWithdrawBtn");
const castleDepositInput = document.getElementById("castleDepositInput");
const castleDepositBtn = document.getElementById("castleDepositBtn");
const castleStorageDisplay = document.querySelector("[data-castle-storage]");
const castleWithdrawArmy = document.querySelector("[data-castle-army]");
const ballistaBuyBtn = document.getElementById("ballistaBuyBtn");
const ballistaUpgradeBtn = document.getElementById("ballistaUpgradeBtn");
const boltBuyBtn = document.getElementById("boltBuyBtn");
const trapStunBuyBtn = document.getElementById("trapStunBuyBtn");
const bridgeBuyBtn = document.getElementById("bridgeBuyBtn");
let castleModalKey = null;
let castleModalPlayerIndex = null;
const castleFeatureButtons = Array.from(document.querySelectorAll("[data-castle-feature]"));
const castleFeatureStatusElems = {};
castleFeatureButtons.forEach(btn => {
  const feature = btn.dataset.castleFeature;
  castleFeatureStatusElems[feature] = document.querySelector(`[data-feature-status="${feature}"]`);
});
const worldEventStatusRoots = Array.from(document.querySelectorAll("[data-world-event-status]"));
const blockedCellNumbers = [739, 709, 679, 650, 620, 591, 562, 505, 504, 477, 476, 450, 449, 448];
const blockedCellKeys = new Set(blockedCellNumbers.map(num => {
  const index = num - 1;
  const x = index % COLS;
  const y = Math.floor(index / COLS);
  return `${x},${y}`;
}));
const grid = {};

function applyCellSize(size) {
  cellSize = size;
  const dimensions = typeof getVisibleWorldDimensions === "function"
    ? getVisibleWorldDimensions()
    : { cols: COLS, rows: ROWS };
  document.documentElement.style.setProperty("--cell-size", `${cellSize}px`);
  document.documentElement.style.setProperty("--cell-font", `${Math.max(10, Math.round(cellSize * 0.25))}px`);
  game.style.width = (dimensions.cols * cellSize) + "px";
  game.style.height = (dimensions.rows * cellSize) + "px";

  const dragonCell = document.querySelector(".dragon-2x2");
  if (dragonCell) {
    dragonCell.style.width = `calc(${cellSize}px * 2)`;
    dragonCell.style.height = `calc(${cellSize}px * 2)`;
  }
  const castleCells = document.querySelectorAll(".castle-2x2");
  castleCells.forEach(cell => {
    cell.style.width = `calc(${cellSize}px * 2)`;
    cell.style.height = `calc(${cellSize}px * 2)`;
  });
}

for (let y = 0; y < ROWS; y++) {
  for (let x = 0; x < COLS; x++) {
    const cell = document.createElement("div");
    cell.className = "cell inactive";
    cell.style.left = (x * cellSize) + "px";
    cell.style.top  = (y * cellSize) + "px";
    cell.textContent = "";
    const coordLabel = document.createElement("span");
    coordLabel.className = "cell-coords";
    coordLabel.textContent = `${(x + 1).toString().padStart(2, "0")}:${(y + 1).toString().padStart(2, "0")}`;
    cell.appendChild(coordLabel);

    const key = `${x},${y}`;
    cell.dataset.key = key;
    if (blockedCellKeys.has(key)) {
      cell.classList.add("blocked");
    }
    grid[key] = cell;
    game.appendChild(cell);
  }
}
